artifact_uri: file:///Volumes/Data/projects/log-analysis-system/stores/model/957499769591532233/10074aeffd9e4cb8a03ef0b78e26b5aa/artifacts
end_time: 1685717140802
entry_point_name: ''
experiment_id: '957499769591532233'
lifecycle_stage: active
run_id: 10074aeffd9e4cb8a03ef0b78e26b5aa
run_name: window_size_?_test_size_?
run_uuid: 10074aeffd9e4cb8a03ef0b78e26b5aa
source_name: ''
source_type: 4
source_version: ''
start_time: 1685717140788
status: 4
tags: []
user_id: ngohongthai
