artifact_uri: file:///Volumes/Data/projects/log-analysis-system/stores/model/957499769591532233/aa3dce8dbdac4cb5b554cb9df403917e/artifacts
end_time: 1685675005483
entry_point_name: ''
experiment_id: '957499769591532233'
lifecycle_stage: active
run_id: aa3dce8dbdac4cb5b554cb9df403917e
run_name: window_size_?_test_size_?
run_uuid: aa3dce8dbdac4cb5b554cb9df403917e
source_name: ''
source_type: 4
source_version: ''
start_time: 1685672894350
status: 4
tags: []
user_id: ngothai
