artifact_uri: file:///Volumes/Data/projects/log-analysis-system/stores/model/957499769591532233/7ce345ccb2c546a7be560c96bcbc1098/artifacts
end_time: 1685693441355
entry_point_name: ''
experiment_id: '957499769591532233'
lifecycle_stage: active
run_id: 7ce345ccb2c546a7be560c96bcbc1098
run_name: window_size_?_test_size_?
run_uuid: 7ce345ccb2c546a7be560c96bcbc1098
source_name: ''
source_type: 4
source_version: ''
start_time: 1685691639642
status: 3
tags: []
user_id: ngothai
