artifact_uri: file:///Volumes/Data/projects/log-analysis-system/stores/model/957499769591532233/3bf50b19889a45d2b6126ddef6d2dfea/artifacts
end_time: 1685750158938
entry_point_name: ''
experiment_id: '957499769591532233'
lifecycle_stage: active
run_id: 3bf50b19889a45d2b6126ddef6d2dfea
run_name: window_size_?_test_size_?
run_uuid: 3bf50b19889a45d2b6126ddef6d2dfea
source_name: ''
source_type: 4
source_version: ''
start_time: 1685750024810
status: 4
tags: []
user_id: ngohongthai
